### ISSUE TITLE
NC pins not connected to ground

### ISSUE THREAD

**Issue by madvoid** [adafruit/Adafruit-DS3231-Precision-RTC-Breakout-PCB#1]
On page 9 of the most recent [datasheet](https://datasheets.maximintegrated.com/en/ds/DS3231.pdf) for the DS3231, it is stated that the all the No Connection (NC) pins must be connected to ground. However, it does not appear that the pins are connected this way on the breakout board. This is probably not a big deal as all the boards I've tried work well, but I just thought I'd put it out there. Thanks!

\- NG

**Comment by ladyada** [comment]
heh - thats a very exotic use of the phrase "No connection" :D

**Comment by madvoid** [comment]
Ha, very true! I'm going to mark this as closed, thanks again.

**Comment by ladyada** [comment]
kthx - will update next time we do a PCB rev - no ETA at this time!

**Comment by fpgaminer** [comment]
I don't know if it's appropriate to necro a closed issue, but I noticed this same "bug" today.  I thought it might be worth bringing it up again in case it got forgotten?

_(I have no idea what affect this bug might have on the DS3231, but the datasheet does mention the need to ground those pins several times)_

**Comment by ladyada** [comment]
oops yeah we forgot to revise, next PCB run for sure :)
